### ISSUE TITLE
Implement UI to change the application name after it is created.

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#1]
Currently, we can only change the name when we create a new application. We should add a editor to change the name after we create it inside the applicaiton page. We can add an edit button after the name to popup a window to change the name of the application.

**Comment by pencilcheck** [comment]
I am looking at several candidates, and this one jumps out of the rest:
http://vitalets.github.io/x-editable/

**Comment by wycc** [comment]
Looks good.

2013/8/28 Penn Su notifications@github.com

**Comment by pencilcheck** [comment]
Implemented in commit 317df90
