### ISSUE TITLE
Set location incorrectly

### ISSUE THREAD

**Issue by cheweiliang** [wukong-m2m/wukong-darjeeling#102]
When clicking "set location" button in the node location, it will set the location incorrectly.

In monitor-nodes.html, line 73:
$('.set-location').click(function() {
  var tmp_loc = $(this).prev().val();
}

$(this) is the "Set Location" button
$(this).prev() will be "Find Location" button
$(this).prev().prev() will be the input text.

The location value will be passed from "Find Location"
I think the location value should be passed by input text.
Maybe it should be like:
tmp_loc = $(this).prev().prev().val();
so the location will be passed from the input text.

**Comment by senatorjo** [comment]
Nice catching. Modified in commit f253d9130465d0ea22a31afc2468d389f6d92226 as suggested:)

**Comment by cheweiliang** [comment]
Yes, I saw it.

Can someone else test it to make sure if it is fixed, thx?
