### ISSUE TITLE
Location of first wunode will be set by the "find location" button of other wunode

### ISSUE THREAD

**Issue by cheweiliang** [wukong-m2m/wukong-darjeeling#109]
Whenever I want to use "find location" to set the location string, it will always set the location string to the first wunodes instead of the wunode I chose.

For example, I clicked the "find location" of the third wunode, but it set the location to the first wunode.

![screen shot 2013-11-12 at 7 37 56](https://f.cloud.github.com/assets/1559930/1521251/05557516-4b8f-11e3-868c-fd2ad3a774c0.png)

![screen shot 2013-11-12 at 7 38 09](https://f.cloud.github.com/assets/1559930/1521252/0a119ee0-4b8f-11e3-8f62-510d74dd7875.png)

**Comment by cheweiliang** [comment]
In 7a2c03c, the dialog is not shown when I click the "Find Location" button.
Please check it again, thank you.

**Comment by senatorjo** [comment]
Should be working now. Hope this fix doesn't create more issues XD.
