### ISSUE TITLE
Master crashes when an unknown wuclass ID is found in nodes.xml or during discovery.

### ISSUE THREAD

**Issue by nielsreijers** [wukong-m2m/wukong-darjeeling#138]
I'm refactoring the standard library and reorganising the ids a bit. There was a cached discovery result in nodes.xml, which has an wuclass id that doesn't exist anymore. This caused the master to crash. It would be better if it just does a rediscovery if it finds the information in nodes.xml is incorrect.

When doing the rediscovery, one of the nodes had some old code, including a virtual Or gate on it. Since I changed this ID, the master can't find the wuclass, and crashes instead. It should just list it as an "Unknown WuClass" or something similar.

**Comment by senatorjo** [comment]
A message about error wuclass type will be displayed in the master console. It would be complex if the exception is throwed further away, so I just choose to do rediscovery if nodes.xml is not valid.

**Comment by nielsreijers** [comment]
Hi Sen,

Thanks for solving this so quickly! I have another issue with the master.
Could you have a quick look at #140 as well?

Best,
 Niels

On Wed, Mar 5, 2014 at 8:51 AM, Sen notifications@github.com wrote:

> A message about error wuclass type will be displayed in the master
> console. It would be complex if the exception is throwed further away, so I
> just choose to do rediscovery if nodes.xml is not valid.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/138#issuecomment-36698363
> .

## 

_
