### ISSUE TITLE
Two threshold objects get mapped to the same port

### ISSUE THREAD

**Issue by nielsreijers** [wukong-m2m/wukong-darjeeling#144]
Create any FBP with two Thresholds. The mapper maps them to the same node and port, so we end up with just 1 threshold.

**Comment by senatorjo** [comment]
It is basically because mappings of previous components was not really recorded, so a second component would reuse the same port. Fortunately, my previous code for resolving this issue was simply commented rather than deleted. Working on refactoring it to fit the new data structure.
