### ISSUE TITLE
Mapper creates native wuobjects when it finds a virtual wuclass.

### ISSUE THREAD

**Issue by nielsreijers** [wukong-m2m/wukong-darjeeling#146]
When we deploy an application and the mapper uses a virtual wuclass because no native one was found, it works for the first time.
However, when deploying the same app a second time, the mapper will see there's an wuclass available, and create a native wuobject. This is incorrect, and causes the program to break since after deploying the new code, the virtual wuclass will be gone unless we include it again.
The mapper should only create a native wuobject when there's a native wuclass available on the node.

**Comment by senatorjo** [comment]
For #146, nielsreijers 's fix may have this problem: 
the list of wuclasses on a node is actually a list of wuclassdefs. In wuclassdefs, the property 'virtual' means if there exists a virtual(java) version of wuclass implementation in master. So this property virtual equals to true doesn't necessary mean the wuclass is virtual in the node. Maybe it's a native(c) wuclass, but there are also java versions available in master. In the former case, wuobjects created from it would be native; in the latter case, wuobjs created would be virtual.

**Comment by nielsreijers** [comment]
Thanks Sen. I'm using your fix now.

On Mon, Mar 17, 2014 at 2:29 PM, Sen notifications@github.com wrote:

> For #146 https://github.com/wukong-m2m/wukong-darjeeling/issues/146,
> nielsreijers 's fix may have this problem:
> the list of wuclasses on a node is actually a list of wuclassdefs. In
> wuclassdefs, the property 'virtual' means if there exists a virtual(java)
> version of wuclass implementation in master. So this property virtual
> equals to true doesn't necessary mean the wuclass is virtual in the node.
> Maybe it's a native(c) wuclass, but there are also java versions available
> in master. In the former case, wuobjects created from it would be native;
> in the latter case, wuobjs created would be virtual.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/146#issuecomment-37788094
> .

## 

_

**Comment by senatorjo** [comment]
:)
