### ISSUE TITLE
Modify the LED wuclass to support passive mode

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#15]
When the refresh_rate is 0, it should use the port1-port4 to decide the state of the LED.

**Comment by wycc** [comment]
Please try to change this to make the LED wuclass more useful.

**Comment by senatorjo** [comment]
I am not sure about the description here. Can you explain more about what's the desired behaviour of the LED class?

**Comment by wycc** [comment]
It looks like the current LED wuclass has been able to do this since it use
the PORT1-PORT4 to control the on/off of the LED already. We can close this
one now.

2013/12/12 senatorjo notifications@github.com
