### ISSUE TITLE
Segmentation fault happened when deploying application to Galileo board

### ISSUE THREAD

**Issue by chingchichuang** [wukong-m2m/wukong-darjeeling#164]
There is a problem about deploying application to Galileo board through the network server.
The method I used to figure out the problem is to checkout to the previous commit until the application running without problems.
The last commit running without problem is 7567af9b034c28813b44fa02d270260256946b5e
But the commit after this one would occur several errors during deploying application.
For the detailed information, please refer to the following link:
https://drive.google.com/file/d/0B8ClMnB4YRocaEtBWXVGZG56Rnc/edit?usp=sharing

**Comment by nielsreijers** [comment]
Chingchi, is this still an issue? We're not using the network server anymore for Galileo, right?
I'm closing it for now, but feel free to reopen the issue if I need to look at it.

**Comment by chingchichuang** [comment]
Dear Niels,

I have already forgot this one:)
However, Ginger and I used network server with Edison board to prepare F2F
demo in last summer.
So, this combination is very useful if we don't want to use gateway.
But back to this issue, I really don't know what was happened at that time@@

Best regards,
Ching Chi
