### ISSUE TITLE
Experimenting with Gradle build

### ISSUE THREAD

**Issue by nielsreijers** [wukong-m2m/wukong-darjeeling#168]
Ant's quite restrictive sometimes, for example linking in a library only for the Edison build is quite clumsy. So clumsy I gave up and ended up just copying the sources I needed into the Darjeeling repository.
Also, the builds seem to take longer than they should.

I'm curious if Gradle would be a better choice.

**Comment by wycc** [comment]
The ANT building system right now is quite restricted. For example, if we
want to build picokong library for arduino at wudevice, we need to create
an directory for it. This will produce a lot of directories for library X
at configure Y at hardware Z.

It would be better to make pickong/nanokong,arduino as parameters when we
switch to gradle. The directory is for platform only.

YC

Phone: 886-2-23516989
Mobile: 0919816155

2015-05-01 12:45 GMT+08:00 Niels Reijers notifications@github.com:

**Comment by nielsreijers** [comment]
What's the problem with having config directories? Do we need to add configurations that often? Also, if we change things as target platform, apps, and included libaries to be command line parameters, we still need a place to put the config.h and main.c files, or do you have an idea to refactor that as well?

The Gradle build is almost finished, but the configuration part is the only thing I haven't touched yet. Right now it can only build one, and from the root directory. You can have a look one the gradle-build branch. This branch is taken from my rtc branch though, so it's a year behind develop.
For my work this is about good enough, but if you think it's useful to port to the main branch we can do that. It's not compatible with the Ant build though, so that will have to go.

**Comment by wycc** [comment]
Currently, in the config directory, we have a couple of different
dimensions. Firstly, we have nanokong/picokong. Secondly, we have platform,
such as wunode/galileo/native. Third, we have arduino library/executable.
Totally, we have 2x3x2=12 different configurations at least.

It's better to leave the platform in this directory only and make the
nanokong/picokon, arduino library/executable as different options of build
targets.

2015-05-09 15:53 GMT+08:00 Niels Reijers notifications@github.com:
