### ISSUE TITLE
Implement a import component feature to include components from other page.

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#17]
In order to link pages together. We need to able to import components from other pages.

**Comment by pencilcheck** [comment]
We have to be careful to not make things complicated. I thought pages share the same app context so if I have custom components in one app, shouldn't I be able to use it in all pages in the app?

**Comment by wycc** [comment]
I don't think that the custom components has anything special. Once is it
craeted in the page, we can use it all pages like standard components.

2013/8/31 Penn Su notifications@github.com
