### ISSUE TITLE
Update the message in the deploy page of the wuclass desiogner incrementally.

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#2]
Both build and upload won't show anything before the action is finished. We should put the ant in the background and then let the UI poll the current message so that we can show the message incrementally.

**Comment by pencilcheck** [comment]
You could use existing functions that I wrote for handling ajax and periodic polling. Don't need to write another one.

**Comment by cheweiliang** [comment]
Resolved by @wycc at commit: a1ba49d
