### ISSUE TITLE
After include/exclude a device, we need to update the model

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#20]
We may need to notify the location tree as well.

**Comment by pencilcheck** [comment]
Please assign this to students who are much more familiar with the Include/exclude mechanisms. I believe the the code is not that hard to change to update the models.

**Comment by wycc** [comment]
Please find one and work with him. I don't think that they really know how
to update the model correctly. You may work with ®¶¾± for this¡C

2013/11/5 Penn Su notifications@github.com

**Comment by pencilcheck** [comment]
The name is gibberish on my end.

**Comment by wycc** [comment]
Please try to make an example of how to update an individual wudevice. I believe that we can simplily call getNodeInfo and change the create method of the WuNode to return the old WuNode if it exists. We need to settle this down soon.

BTW, I hope that we don't need to perform discovery at all when we start the Master. It should simplily load WuNodes from the database.

**Comment by senatorjo** [comment]
Node info lists will be updated in UpdateAllNodeInfos() function in wkpfcomm. When UpdateAllNodeInfos() is called, it will use getNodeInfo(id) which updates in0memory data structure.
