### ISSUE TITLE
In the map, we will show the previous results without any indication that the mapper is still working.

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#22]
We should remove the previous result and show a busy message or change the cursor to be busy.

**Comment by pencilcheck** [comment]
I suggest that we move all UI design related feature requests into a separate branch.

**Comment by wycc** [comment]
I think that this has been addressed, isn't it?  For now, we will list
unmapped components in different color. Is this is the case, we have
addressed this issue.

2013/11/5 Penn Su notifications@github.com

**Comment by wycc** [comment]
I think in the wrong way for this bug. I think that we should clear the first and show waiting on the UI. I don't think that this is big item so that we really need a branch.

However, it is always OK to have branch in git since it's almost free.

**Comment by pencilcheck** [comment]
If this has been addressed then I will close the issue.

I think UI and the overall user experience design is still very important to us since we are building a user facing product. We need to be careful on that
