### ISSUE TITLE
The mapper do not prefer the native wuobject.

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#23]
Currently, the mapper will choice wuobject if it exists. However, if we have two devices matched by the locationtree, the mapper might select the device with virtual wuclass if its node_id is smaller. We should change the mapper to sort all candidates.

**Comment by pencilcheck** [comment]
I'm sorting the node.wuclasses() and node.wuobjects() using sorted by the virtual key.
sorted is ascending by default.

That should do it. Will commit soon.

**Comment by pencilcheck** [comment]
Committed at f4a07015d9. Please check.
