### ISSUE TITLE
The Java WuClass is not working

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#25]

**Comment by pencilcheck** [comment]
After a brief inspection, I concluded that the UI is buggy.

https://github.com/wukong-m2m/wukong-darjeeling/issues/37
https://github.com/wukong-m2m/wukong-darjeeling/issues/35
https://github.com/wukong-m2m/wukong-darjeeling/issues/34
https://github.com/wukong-m2m/wukong-darjeeling/issues/32
https://github.com/wukong-m2m/wukong-darjeeling/issues/31
https://github.com/wukong-m2m/wukong-darjeeling/issues/29

**Comment by wycc** [comment]
Can you verify if it works without the UI?

2013/9/7 Penn Su notifications@github.com

**Comment by pencilcheck** [comment]
Yes, we just need to make sure ant tasks are calling the appropriate
commands to generate the java classes for the wuclasses then the rest would
be up to UI

On Saturday, September 7, 2013, Yu-Chung Wang wrote:

> Can you verify if it works without the UI?
> 
> 2013/9/7 Penn Su <notifications@github.com <javascript:_e({}, 'cvml',
> 'notifications@github.com');>>
> 
> > After a brief inspection, I concluded that the UI is buggy.
> > 
> > #37 https://github.com/wukong-m2m/wukong-darjeeling/issues/37
> > #35 https://github.com/wukong-m2m/wukong-darjeeling/issues/35
> > #34 https://github.com/wukong-m2m/wukong-darjeeling/issues/34
> > #32 https://github.com/wukong-m2m/wukong-darjeeling/issues/32
> > #31 https://github.com/wukong-m2m/wukong-darjeeling/issues/31
> > #29 https://github.com/wukong-m2m/wukong-darjeeling/issu%20es/29
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/wukong-m2m/wukong-darjeeling/issues/25#issuecomment-23991527>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/25#issuecomment-23991632
> .

## 

_--_
_Penn Su_
National Taiwan University
Department of Computer Science

**Comment by wycc** [comment]
Post it as soon as it works. I will fix all UI issues very soon.

2013/9/7 Penn Su notifications@github.com

**Comment by wycc** [comment]
Have you test the Java version of the WuClass, such as Thresold, AndGate? Others report that they are not working.

**Comment by pencilcheck** [comment]
What's the current status of Java WuClasses? I think they are fixed.

**Comment by chishengshih** [comment]
@pencilcheck It seems that the last comment is asking if you test the Java version of WuClass. The ones checking WuClass in the last few months may not read this message and will NOT answer your questions. 

In last meeting, Ken or Louis are asked to prepare the list of checked WuClass. Please check with Ken or Louis to find out the status. 

@louisccc @catlikethief Who has the list of checked WuClass?

**Comment by cheweiliang** [comment]
@chishengshih Do you mean this file that list the tested WuClass a few month ago?
https://docs.google.com/spreadsheet/ccc?key=0At0U89ankPgcdGlzUEZTNWFVUlZGSnZLZUVZRU1EY3c&usp=drive_web#gid=0

**Comment by chishengshih** [comment]
Yes, this is the one. 

However, I suggested to add for each wuclass.
1. Version being tested.
2. Testing report. 
3. Date/Time being tested. 
4. Error message or Issue # for the error if there is any. 

Can this file be added to the development branch?

Daniel

On Nov 4, 2013, at 10:43 AM, catlikethief notifications@github.com wrote:

> @chishengshih Do you mean this file that list the tested WuClass a few month ago?
> https://docs.google.com/spreadsheet/ccc?key=0At0U89ankPgcdGlzUEZTNWFVUlZGSnZLZUVZRU1EY3c&usp=drive_web#gid=0
> 
> —
> Reply to this email directly or view it on GitHub.

---

Chi-Sheng (Daniel) Shih
NEWS Lab, National Taiwan University
E-Mail: cshih@csie.ntu.edu.tw

## Phone: +886-2-33664927 Fax: +886-2-33663778

**Comment by pencilcheck** [comment]
@catlikethief should work on this issue as their team is right on testing and developing the WuClasses.

**Comment by cheweiliang** [comment]
I used the commit c07098a in release0.2 branch with an application with a virtual and gate.
It seemed that the Java WuClass worked.
