### ISSUE TITLE
Verify the function to build custom Java wuclass

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#3]

**Comment by pencilcheck** [comment]
Should be easily solved by making sure the commands used to compile java files include the path to the custom java wuclasses. I am not sure where they are stored btw.

**Comment by wycc** [comment]
We have discussed this for more than one month. Please don't tell me that
you have no idea. If you do, I can show you. Or you can ask Niels. Please
try to write a simple custom Java which can be used to control the on board
LED as example.  I want to include it in the wuclass toturial.

2013/8/31 Penn Su notifications@github.com

**Comment by pencilcheck** [comment]
No, I mean that I probably don't know if there are other places that I could miss, but I know where they are when we are fixing the UI last Tues. meeting

**Comment by wycc** [comment]
What we need to do is to verify if the custom Java class will be compiled
and included or not. As I put in the description, I hope to write a custom
java wuclass which can control the ob board LED as demo of this concept.

2013/8/31 Penn Su notifications@github.com

**Comment by pencilcheck** [comment]
Compiling custom wuclasses is part of 1.0 milestone, close
