### ISSUE TITLE
Global WuClass Designer still can let user select type for a wuclass

### ISSUE THREAD

**Issue by pencilcheck** [wukong-m2m/wukong-darjeeling#30]
We should remove that option to select "type" for a wuclass as we have discussed before.

**Comment by wycc** [comment]
Please explain it. Are you saying to remove the Save button or what?

2013/9/7 Penn Su notifications@github.com

> We should remove that option to select "type" for a wuclass as we have
> discussed before.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/30
> .

## 

YC

Phone: 886-2-23516989
Mobile: 0919816155

**Comment by pencilcheck** [comment]
When you are editing for a wuclasses it lets you select the "type" for the wuclasses with the options given "Software", "Hardware" which we have discussed before to ignore and leave only native and virtual options. Isn't it?

**Comment by wycc** [comment]
I don't know if the mapper may still need this flag to distinguish the
hardware or software implementation of the same WuClass. However, we may
remove it for now since nobody use it.

2013/9/7 Penn Su notifications@github.com

**Comment by wycc** [comment]
20b1605 

Hide the type editor.
