### ISSUE TITLE
No save options for wuclasses tab in both edit component and wuclass designer

### ISSUE THREAD

**Issue by pencilcheck** [wukong-m2m/wukong-darjeeling#31]
No save for wuclasses, I can't save them.

**Comment by wycc** [comment]
It's in the Type page.

2013/9/7 Penn Su notifications@github.com

> No save for wuclasses, I can't save them.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/31
> .

## 

YC

Phone: 886-2-23516989
Mobile: 0919816155

**Comment by pencilcheck** [comment]
Why is it in the type page? I thought save in type is for saving types, not for wuclasses...

**Comment by wycc** [comment]
Type and WuClass are in the same XML. We can not save the Type data only
and we have no reason to do that either. I would like to add a global Save
and Cancel button in the bottom of the dialog to replace the save button in
the Type.

2013/9/7 Penn Su notifications@github.com

**Comment by pencilcheck** [comment]
Even though they are in the same file, that is not an excuse to put UI as directly reflection of that model.
Users shouldn't care about what's actually implemented. They just want to work with our system without having to confront the nitty gritty of our internal representations.

The UI design should put in more efforts and I think we should consider a new type of workflow in this project to prevent unwanted changes, and maintain higher code quality in the main repo in the future. The basic idea is to resume what github has designed for collaboration - pull requests!. So we should just remove everyone as collaborator and development should be something like this:
1. fork
2. make changes
3. make a pull request in the respective branches.

**Comment by wycc** [comment]
Relocate the Save button to the top bar to make it clear that it will save everything. 7d20467
