### ISSUE TITLE
Global WuClass Editor has a bug with creating multiple new wuclasses

### ISSUE THREAD

**Issue by pencilcheck** [wukong-m2m/wukong-darjeeling#34]
In global WuClass Editor, if you go to Classes tab and try to create a new wuclass it will not show you any GUI hint except for a subtle update by adding at the bottom of the list called "New Class", and if you don't do anything and keep hitting the "New Class" button, more entries will appear with the same name and if you go in one of the created wuclass and try to change something and exit back out, all new entries with the same name will be checked.

**Comment by wycc** [comment]
This has been fixed. 3c9a68d
