### ISSUE TITLE
Save in type (will be changed) does not save implementation

### ISSUE THREAD

**Issue by pencilcheck** [wukong-m2m/wukong-darjeeling#37]
After I create a new wuclass, edit the java source code for the wuclass and hit save, only enabled_wuclass.xml and WuKongStandardLibrary.xml are changed but no where can I find the implementation I just edit.

This issue corresponds to the other issue on the UI https://github.com/wukong-m2m/wukong-darjeeling/issues/35

Should also look after the types as well, they should all be saved

**Comment by wycc** [comment]
The Save All save the XML only. The source code will be saved in the text editor windows. The reason of this issue is related to a bug in the save function. It has been fixed at e50b1da

**Comment by pencilcheck** [comment]
Where are you saving the implementation file to?

Make sure you make the distinction between global and app specific, because now all virtual wuclasses are placed in one directory regardless of visibility (wukong/javax/wukong/virtualwuclasses).

I don't know if building WKDeploy consider that.

**Comment by wycc** [comment]
The application specific wuclass should be in the app directory. For the
global one, it will be in the lib/wkpf/c/common/native_wuclasses and the
java version is in the wukong/javax/wokong/virtualwuclasses.

I have not verify the app specific code yet. Maybe do it in the Tuesday
together.

2013/9/8 Penn Su notifications@github.com
