### ISSUE TITLE
The default property is not generated correctly.

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#5]
We modify the generationof the JAVA only. We should modify the XML generator as well. Currently, this won;t work.

**Comment by pencilcheck** [comment]
I thought we fixed that yesterday, what's the problem now? And please elaborate on this issue.

**Comment by wycc** [comment]
I don't know why it works yesterday. It actually fixed in the wrong
function. There are two generateProperties. You only fix the one for
generate Java code. The one for the XML is not changed.

I test by modify the default property. However, the LED is not changed. You
should try it by yourself.

2013/8/28 Penn Su notifications@github.com
