### ISSUE TITLE
When a device is included or excluded, the discovery result must be updated as well.

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#52]
For now, after we include a device, we can not use it until we restart the master because the WuNode is not updated and we will not discovery the wuclass and wuobject for the new device.

When we delete a device, we can still see it in the Node Editor and LocationTree.

**Comment by chishengshih** [comment]
Is this a bug?

Chi-Sheng Shih
National Taiwan University

**Comment by wycc** [comment]
It's a bug and it is in the tracker already.

2013/10/15 Chi-Sheng (Daniel) Shih notifications@github.com

> Is this a bug?
> 
> Chi-Sheng Shih
> National Taiwan University
>

**Comment by senatorjo** [comment]
This is because cache is used for discovery and is related to database cache things. See issue #51 
Reassigning it to Pencilcheck
