### ISSUE TITLE
Master is broken after saving the C hello world wuclass and restarting the master

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#54]
- Master is broken after saving the C hello world wuclass and restarting the master:
  Scanning /Users/niels/git/darjeeling/wukong/master/../../wukong/ComponentDefinitions/WuKongStandardLibrary.xml
  Constructing basic types
  Scanning types
  Scanning classes & properties
  Traceback (most recent call last):
  File "master_server.py", line 985, in <module>
    Parser.parseLibrary(COMPONENTXML_PATH)
  File "/Users/niels/git/darjeeling/wukong/master/wkpf/parser.py", line 48, in parseLibrary
    return Parser.parseLibraryXMLString(xml.read())
  File "/Users/niels/git/darjeeling/wukong/master/wkpf/parser.py", line 42, in parseLibraryXMLString
    name, datatype, default, access, wuclassdef)
  File "/Users/niels/git/darjeeling/wukong/master/wkpf/models.py", line 251, in create
    wutype = cls.new(number, name, datatype, default, access, wuclassdef)
  File "/Users/niels/git/darjeeling/wukong/master/wkpf/models.py", line 235, in new
    raise Exception('type not found %s' % (datatype))
  Exception: type not found undefined
  Steps to reproduce:
  Create new wuclass
  Add a property, but don’t change anything
  Save
  Stop master server
  Restart master server
  It will choke on:
  <WuClass name="New_Class" id="42" virtual="false" type="soft">
      <property name="undefined" access="undefined" datatype="undefined"  />

**Comment by pencilcheck** [comment]
Can you reformat the error message so it is much readable? Also it seems like you didn't paste the full error trace.

**Comment by nielsreijers** [comment]
Steps to reproduce:

   1.

   Create new wuclass
   2.

   Add a property, but don’t change anything
   3.

   Save
   4.

   Stop master server
   5.

   Restart master server
   6.

   It will choke on:

```
<WuClass name="New_Class" id="42" virtual="false" type="soft">

   <property name="undefined" access="undefined" datatype="undefined"
```

 />
    </WuClass>

On Fri, Nov 1, 2013 at 3:51 PM, Penn Su notifications@github.com wrote:

> Can you reformat the error message so it is much readable? Also it seems
> like you didn't paste the full error trace.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/54#issuecomment-27551766
> .

## 

_

**Comment by nielsreijers** [comment]
Hmm, not as readable as I'd hoped ;-) but it will do I guess.

**Comment by pencilcheck** [comment]
Then I would suggest looking into the creation of wuclass property, seems like there could be a corruption happening during save or that the function that saves the property has some erroneous assumptions.

**Comment by pencilcheck** [comment]
But I will look into it.

**Comment by pencilcheck** [comment]
Looks like the problem is solved, master does not choke on newly created wuclasses now
