### ISSUE TITLE
Fialed at generating XML file

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#6]
The WUXML is (Use Edit too see it)

<application name="c9b87922296af0426eef3799e1a11b07">
<page title="_first_">
    <component type="Loop_delay_short" instanceId="30" x="300" y="139" w="100" h="100">
        <link fromProperty="output" toInstanceId="29" toProperty="port1"/>
        <location requirement="WuKong" />
        <group_size requirement="1" />
        <reaction_time requirement="1" />
        <signalProperty  />
    </component>
    <component type="LED" instanceId="29" x="616" y="125" w="100" h="100">
        <location requirement="WuKong" />
        <group_size requirement="1" />
        <reaction_time requirement="1" />
        <signalProperty refresh_rate="1000" port1="true" port2="false" port3="true" port4="true"  />
    </component>
</page>
</application>

The error is

make-djarchive:
[djarchive] Creating archive '/home/wycc/devel/wukong-darjeeling/src/app/wkdeploy/build/wkdeploy.dja'
[djarchive] Adding '/home/wycc/devel/wukong-darjeeling/src/app/wkdeploy/build/wkdeploy.di'

all:

create-wkpftables:
[wkpftable] java.lang.NumberFormatException: For input string: ""
[wkpftable]     at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
[wkpftable]     at java.lang.Integer.parseInt(Integer.java:470)
[wkpftable]     at java.lang.Short.parseShort(Short.java:120)
[wkpftable]     at java.lang.Short.parseShort(Short.java:78)
[wkpftable]     at org.csiro.darjeeling.wkpftable.ant.WKPFTableTask.makeInitValues(WKPFTableTask.java:217)
[wkpftable]     at org.csiro.darjeeling.wkpftable.ant.WKPFTableTask.execute(WKPFTableTask.java:92)
[wkpftable]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[wkpftable]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[wkpftable]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[wkpftable]     at java.lang.reflect.Method.invoke(Method.java:597)
[wkpftable]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[wkpftable]     at org.apache.tools.ant.Task.perform(Task.java:348)
[wkpftable]     at org.apache.tools.ant.Target.execute(Target.java:390)
[wkpftable]     at org.apache.tools.ant.Target.performTasks(Target.java:411)
[wkpftable]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[wkpftable]     at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
[wkpftable]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[wkpftable]     at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
[wkpftable]     at org.apache.tools.ant.Main.runBuild(Main.java:809)
[wkpftable]     at org.apache.tools.ant.Main.startAnt(Main.java:217)
[wkpftable]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[wkpftable]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by wycc** [comment]
This should be related to we remove the empty string checking when we parse the default values. We should put it back.

**Comment by pencilcheck** [comment]
How do you reproduce it? Is it still there?

**Comment by wycc** [comment]
I believe that this has been solved. It is due to the incorrect XML from the codegen.
