### ISSUE TITLE
The wkpf table generator generate the default property table for the first component only. Others are ignored.

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#7]
Steps
- Add a LED and set the default values. Works as expected.
- Add another loop_defal_boolean. Works as well.
- Set the default value of the loop_delay_bolean. The default property of the LED is not initialized.

**Comment by pencilcheck** [comment]
Ok, I copied generateProperties and overwrite the other one, will test the default values.

**Comment by wycc** [comment]
Please test if this is fixed. I believe so. Otherwise, the FBP will not work except the simplest one.

**Comment by senatorjo** [comment]
Just checked using light sensor->threshold->light actuator. All components will have their non-read-only default value generated, no matter set or unset.
