### ISSUE TITLE
Draw doll house demo scenario FBP

### ISSUE THREAD

**Issue by cheweiliang** [wukong-m2m/wukong-darjeeling#70]
Three scenario:
Bedroom:
If PIR + light dark -> lamp on
If ~PIR + light bright -> lamp off

Living room
If PIR + light-1 dark -> lamp-1 on
If PIR + light-1 bright + light-3 dark -> TV-2 off
If PIR + light-3 bright + light-1 bright -> lamp-1 off

Kitchen
If PIR + temp=high -> fan on
If PIR=off + temp=high + PIRLR=on -> TV-off + fan-on + lightLR-on
If PIR=off + temp=high + PIRBR=on -> TV-off + fan-on + lightBR-on

**Comment by louisccc** [comment]
we've successfully drawn the fbp of doll house to Wukong IDE,

That is a really crazy fbp, please take a glance.

![2013-11-01 2 48 312](https://f.cloud.github.com/assets/934994/1452152/e00c389c-42c1-11e3-95d9-b38140b864cb.png)

**Comment by nielsreijers** [comment]
Looks "impressive"...

Quick question: I see some places where multiple outputs go to the same
input property, mainly at the actuators. I don't think we allowed this
before, so I'm curious what the behaviour will be?

On Fri, Nov 1, 2013 at 2:50 PM, louisccc notifications@github.com wrote:

> we've successfully drawn the fbp of doll house to Wukong IDE,
> 
> That is a really crazy fbp, please take a glance.
> 
> [image: 2013-11-01 2 48 312]https://f.cloud.github.com/assets/934994/1452152/e00c389c-42c1-11e3-95d9-b38140b864cb.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/70#issuecomment-27550294
> .

## 

_

**Comment by wycc** [comment]
Usually, complex FBP should be divided into several page. However, this
mind me that the component import is not implement the the FBP editor yet.
It makes the complex FBP impossible. We should implement it as soon as
possible.

2013/11/1 Niels Reijers notifications@github.com

> Looks "impressive"...
> 
> Quick question: I see some places where multiple outputs go to the same
> input property, mainly at the actuators. I don't think we allowed this
> before, so I'm curious what the behaviour will be?
> 
> On Fri, Nov 1, 2013 at 2:50 PM, louisccc notifications@github.com
> wrote:
> 
> > we've successfully drawn the fbp of doll house to Wukong IDE,
> > 
> > That is a really crazy fbp, please take a glance.
> > 
> > [image: 2013-11-01 2 48 312]<
> > https://f.cloud.github.com/assets/934994/1452152/e00c389c-42c1-11e3-95d9-b38140b864cb.png>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/wukong-m2m/wukong-darjeeling/issues/70#issuecomment-27550294>
> > 
> > .
> 
> ## 
> 
> _
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/70#issuecomment-27561677
> .

## 

YC

Phone: 886-2-23516989
Mobile: 0919816155

**Comment by wycc** [comment]
It looks like the import is there.However, it does not work.

2013/11/2 Yu-Chung Wang wycc@homescenario.com

> Usually, complex FBP should be divided into several page. However, this
> mind me that the component import is not implement the the FBP editor yet.
> It makes the complex FBP impossible. We should implement it as soon as
> possible.
> 
> 2013/11/1 Niels Reijers notifications@github.com
> 
> > Looks "impressive"...
> > 
> > Quick question: I see some places where multiple outputs go to the same
> > input property, mainly at the actuators. I don't think we allowed this
> > before, so I'm curious what the behaviour will be?
> > 
> > On Fri, Nov 1, 2013 at 2:50 PM, louisccc notifications@github.com
> > wrote:
> > 
> > > we've successfully drawn the fbp of doll house to Wukong IDE,
> > > 
> > > That is a really crazy fbp, please take a glance.
> > > 
> > > [image: 2013-11-01 2 48 312]<
> > > https://f.cloud.github.com/assets/934994/1452152/e00c389c-42c1-11e3-95d9-b38140b864cb.png>
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/wukong-m2m/wukong-darjeeling/issues/70#issuecomment-27550294>
> > > 
> > > .
> > 
> > ## 
> > 
> > _
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/70#issuecomment-27561677
> > .
> 
> ## 
> 
> YC
> 
> Phone: 886-2-23516989
> Mobile: 0919816155

## 

YC

Phone: 886-2-23516989
Mobile: 0919816155

**Comment by wycc** [comment]
The import is fixed. Please look at issue #79. I display ID for each
component as well so that we can know components are in the different page
are the same one. I open another issue #81 which add a name for each
component so that we can have have better understanding for using the same
instead of the wuclass type. We can tell the wuclass by using the
properties below. Display the type is kind of duplicated for the precious
screen estate.

2013/11/2 Yu-Chung Wang wycc@homescenario.com

> It looks like the import is there.However, it does not work.
> 
> 2013/11/2 Yu-Chung Wang wycc@homescenario.com
> 
> > Usually, complex FBP should be divided into several page. However, this
> > mind me that the component import is not implement the the FBP editor yet.
> > It makes the complex FBP impossible. We should implement it as soon as
> > possible.
> > 
> > 2013/11/1 Niels Reijers notifications@github.com
> > 
> > > Looks "impressive"...
> > > 
> > > Quick question: I see some places where multiple outputs go to the same
> > > input property, mainly at the actuators. I don't think we allowed this
> > > before, so I'm curious what the behaviour will be?
> > > 
> > > On Fri, Nov 1, 2013 at 2:50 PM, louisccc notifications@github.com
> > > wrote:
> > > 
> > > > we've successfully drawn the fbp of doll house to Wukong IDE,
> > > > 
> > > > That is a really crazy fbp, please take a glance.
> > > > 
> > > > [image: 2013-11-01 2 48 312]<
> > > > https://f.cloud.github.com/assets/934994/1452152/e00c389c-42c1-11e3-95d9-b38140b864cb.png>
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/wukong-m2m/wukong-darjeeling/issues/70#issuecomment-27550294>
> > > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > _
> > > 
> > > —
> > > Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/70#issuecomment-27561677
> > > .
> > 
> > ## 
> > 
> > YC
> > 
> > Phone: 886-2-23516989
> > Mobile: 0919816155
> 
> ## 
> 
> YC
> 
> Phone: 886-2-23516989
> Mobile: 0919816155

## 

YC

Phone: 886-2-23516989
Mobile: 0919816155
