### ISSUE TITLE
Drawing too many components in FBP editor facing error

### ISSUE THREAD

**Issue by louisccc** [wukong-m2m/wukong-darjeeling#72]
Whenever I create too many components in FBP editor. I face the error.
I tracked it from the Broswer's console, and find it's from block.js:171

Error message, 
Uncaught TypeError: Cannot read property 'index' of undefined 

Could Dr. Wang @wycc help me out this issue? I need to pass this issue in order to finish fbp application.

Related #70

**Comment by chishengshih** [comment]
Louis, 

Please provide detail information of the crash. The screenshot of FBP is one example. 

In addition, the FBP for the demo seems to be very simple. Do these simple FBPs cause trouble? If not, you should not wait for Dr. Wang's response and continue to draw the FBP.

**Comment by chishengshih** [comment]
Louis,

Please provide detail information of the crash. The screenshot of FBP is one example.

In addition, the FBP for the demo seems to be very simple. Do these simple FBPs cause trouble? If not, you should not wait for Dr. Wang's response and continue to draw the FBP.

Daniel

On 2013/10/30, at 下午1:26, louisccc notifications@github.com wrote:

> Whenever I create too many components in FBP editor. I face the error.
> I tracked it from the Broswer's console, and find it's from block.js:171
> 
> Error message, 
> Uncaught TypeError: Cannot read property 'index' of undefined
> 
> Could Dr. Wang @wycc help me out this issue? I need to pass this issue in order to finish fbp application.
> 
> Related #70
> 
> —
> Reply to this email directly or view it on GitHub.

---

Chi-Sheng (Daniel) Shih
NEWS Lab, National Taiwan University
E-Mail: cshih@csie.ntu.edu.tw

## Phone: +886-2-33664927 Fax: +886-2-33663778

**Comment by louisccc** [comment]
Sorry for @chishengshih , I have to say yes,
I can show the FBP I draw, It's simple, really. 

This is the one, it seems okay if i really put two or three components on it.
![2013-10-30 9 53 49](https://f.cloud.github.com/assets/934994/1437277/bee780b6-416a-11e3-98c2-af598d8f1135.png)

But when I put the essential components on FBP editor. It acts like this screenshot.
![2013-10-30 9 55 39](https://f.cloud.github.com/assets/934994/1437296/ff586066-416a-11e3-8621-d7f905d7ffb3.png)

this issue is disastrous for me. When there are three or less components in FBP editor, it's okay if i do anything(Drag, add link, delete component, ... etc) When I added four or more, it seems something went wrong.

**Comment by wycc** [comment]
Is this related to number of components or a specific component? I guess
that it should be related to the AND_GATE or PIR which is not really used
before.

2013/10/30 louisccc notifications@github.com

**Comment by wycc** [comment]
Try to cange the signals to actions in the line 171.

2013/10/31 Yu-Chung Wang wycca1@gmail.com

**Comment by chishengshih** [comment]
Louis, 

Please check and report if it is caused by AND_GATE or PIR. 

Daniel
On 2013/10/31, at 上午8:30, Yu-Chung Wang notifications@github.com wrote:

> Try to cange the signals to actions in the line 171. 
> 
> 2013/10/31 Yu-Chung Wang wycca1@gmail.com 
> 
> > Is this related to number of components or a specific component? I guess 
> > that it should be related to the AND_GATE or PIR which is not really used 
> > before. 
> > 
> > 2013/10/30 louisccc notifications@github.com 
> > 
> > > Sorry for @chishengshih https://github.com/chishengshih , I have to 
> > > say yes, 
> > > I can show the FBP I draw, It's simple, really. 
> > > 
> > > This is the one, it seems okay if i really put two or three components on 
> > > it. 
> > > [image: 2013-10-30 9 53 49]https://f.cloud.github.com/assets/934994/1437277/bee780b6-416a-11e3-98c2-af598d8f1135.png 
> > > 
> > > But when I put the essential components on FBP editor. It acts like this 
> > > screenshot. 
> > > [image: 2013-10-30 9 55 39]https://f.cloud.github.com/assets/934994/1437296/ff586066-416a-11e3-8621-d7f905d7ffb3.png 
> > > 
> > > this issue is disastrous for me. When there are three or less components 
> > > in FBP editor, it's okay if i do anything(Drag, add link, delete component, 
> > > ... etc) When I added four or more, it seems something went wrong. 
> > > 
> > > — 
> > > Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/72#issuecomment-27390884 
> > > . 
> > 
> > —
> > Reply to this email directly or view it on GitHub.

---

Chi-Sheng (Daniel) Shih
NEWS Lab, National Taiwan University
E-Mail: cshih@csie.ntu.edu.tw

## Phone: +886-2-33664927 Fax: +886-2-33663778

**Comment by wycc** [comment]
I have responsed this issue in the other comment. Please try to change the
signals to the actions. If this works, commit it into the git and close
this issue.

2013/10/31 Chi-Sheng (Daniel) Shih notifications@github.com

> Louis,
> 
> Please check and report if it is caused by AND_GATE or PIR.
> 
> Daniel

**Comment by louisccc** [comment]
I succeed, thank you.
