### ISSUE TITLE
Exporting Fbp to a file 

### ISSUE THREAD

**Issue by louisccc** [wukong-m2m/wukong-darjeeling#73]
This is a minor issue, 

Do we have any mechanism that we can share our fbp to other?

For example, @hanboa Hans is cooperating with me drawing the fbp of doll house demo, I want to show him what I draw but find no way other than screenshot.

If not, then I will try to implement this feature when available. 
Any comment?

**Comment by chishengshih** [comment]
I don't think we have it. Go ahead and do it.

Daniel
On 2013/10/31, at 上午11:08, louisccc notifications@github.com wrote:

> This is a minor issue,
> 
> Do we have any mechanism that we can share our fbp to other?
> 
> For example, @hanboa Hans is cooperating with me drawing the fbp of doll house demo, I want to show him what I draw but find no way other than screenshot.
> 
> If not, then I will try to implement this feature when available. 
> Any comment?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Chi-Sheng (Daniel) Shih
NEWS Lab, National Taiwan University
E-Mail: cshih@csie.ntu.edu.tw

## Phone: +886-2-33664927 Fax: +886-2-33663778

**Comment by senatorjo** [comment]
A walk-around is go to your wukong/apps folder. find your [app] folder there (should be in some weird name like f92ea1839dc16d7396db358365da7066). and copy the [apps].xml. You can open the xml file checking its content to verify it is the one you want.

**Comment by wycc** [comment]
The application should be able to be copied to another machine for testing.
It should working fine in the WebUI once you put the files in the new
master.

2013/11/1 senatorjo notifications@github.com

> A walk-around is go to your wukong/apps folder. find your [app] folder
> there (should be in some weird name like f92ea1839dc16d7396db358365da7066).
> and copy the [apps].xml. You can open the xml file checking its content to
> verify it is the one you want.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/73#issuecomment-27538895
> .

## 

YC

Phone: 886-2-23516989
Mobile: 0919816155

**Comment by chishengshih** [comment]
We discuss these approaches yesterday. We want to find a better way to share it. Eventually, we should user to share their applications over internet.  

Chi-Sheng Shih
National Taiwan University

**Comment by louisccc** [comment]
Copy the directory with hash name is of course a solution to share fbp, 

but is not a friendly way for the user in the future, isn't it?
I think it should be simple if we share via 

```
1. fbp example directory. 

2. 

An export button embedded in application item from main page for user to download compressed fbp application    directory. And, 

An import button on top of the main webpage's application.

Then user can download fbps from others, then upload the compressed file to master, and finally make use of the fbp.
```

If okay I will implement it soon since it's very simple.

**Comment by louisccc** [comment]
Have implemented this feature. 

See the a screenshot here. Now we have many example application section.
![image](https://f.cloud.github.com/assets/934994/1795780/d16338c0-6a37-11e3-90d3-5e1ea5e409da.png)

One we click on the example application, it will pop up one dialog and ask you to enter new application name. Then will copy the example application to your local app directory.

**Comment by senatorjo** [comment]
Hello Louis,

Thanks for the change. It looks good.
Would you please also add the FBP examples into release0.2 branch?
Thanks.

Sen

**Comment by louisccc** [comment]
Found some bugs, reopen this issue.

**Comment by louisccc** [comment]
fixed
