### ISSUE TITLE
Implement or_gate wuclass

### ISSUE THREAD

**Issue by louisccc** [wukong-m2m/wukong-darjeeling#74]
When I draw the fbp for doll house demo. 
I found that there is no or_gate definition in WuKongStandardLibrary.xml
also i search the native wuclass definition in NanoKong project. 

Seems nobody has ever used this wuclass. Is there anyway to achieve or function based on current components definition we have ?

Related issue #70

**Comment by wycc** [comment]
Is this part of the logic wuclass?

2013/11/1 louisccc notifications@github.com

> When I draw the fbp for doll house demo.
> I found that there is no or_gate definition in WuKongStandardLibrary.xml
> also i search the native wuclass definition in NanoKong project.
> 
> Seems nobody has ever used this wuclass. Is there anyway to achieve the or
> function based on components we have currently?
> 
> Related issue #70https://github.com/wukong-m2m/wukong-darjeeling/issues/70
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wukong-m2m/wukong-darjeeling/issues/74
> .

## 

YC

Phone: 886-2-23516989
Mobile: 0919816155

**Comment by curtis1213** [comment]
Yes, the and gate and or gate is usable in logic wuclass.

**Comment by curtis1213** [comment]
There are also XOR and NOT in logic wuclass.

**Comment by louisccc** [comment]
That is an alternative currently. 

But I am confused why i should feed four inputs.(That works if I feed two "true" to input3 and input4).
