### ISSUE TITLE
How to add new location instead of landmark

### ISSUE THREAD

**Issue by louisccc** [wukong-m2m/wukong-darjeeling#78]
![2013-11-01 3 08 56](https://f.cloud.github.com/assets/934994/1452216/a976329e-42c4-11e3-9745-570f3ccbfa35.png)

Now we can only add landmark rather than have node location. How can we add new location, like "Livingroom", to the location field of each component. 

related issue #70

**Comment by cheweiliang** [comment]
You need to use "node location" to add new location.

**Comment by louisccc** [comment]
How 

![image](https://f.cloud.github.com/assets/934994/1452270/c0df4676-42c6-11e3-916d-e13c0702f529.png)

**Comment by senatorjo** [comment]
Under location, enter /Wukong/Bedroom, and "set location". Then the path would be added.
