### ISSUE TITLE
Make the wuclass name shorter so that it can be fit into the title of the block in the FBP editor.

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#80]
Some of the wuclass has very long name. This make it unreadable in the FBP editor and we have no space to display the ID. We should change the name of all wuclass to be less than 7 characters. For example,

Condition_selector_bollean ---> cond_bool
COndition_selector_shart --> cond_short

**Comment by louisccc** [comment]
@wycc 
I found a problem that the fbp editor can not be extended. 

That means when drawing application on the screen, I can only use fbp editor with screen-size to drag my components. I can not scroll down or scroll right for more area.

**Comment by wycc** [comment]
For now, we can not scroll the view. It's not difficult to implement it.
Actually, we only need to remove the overflow:hidden CSS from the canvas.
However, if there is too many components, we should use multiple page
instead. Put everything in a single page is not a good way to write a FBP.

2013/11/3 louisccc notifications@github.com

**Comment by wycc** [comment]
Niels, please help to give each wuclass sharter name.

**Comment by nielsreijers** [comment]
Since this is +2 years old, and lots of work has been done on the FBP editor since, I'm going to assume this is either done or no longer necessary. I'll close the issue, but feel free to reopen it if I need to look at it again.
