### ISSUE TITLE
Deploy the application fail

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#84]
This is due to the src/app/wkdeploy/java directory is not existed.

**Comment by senatorjo** [comment]
Addressed in abc9bb4af7f7dd611a9a9e31571ec05c2ef8173b, however, I am not sure if it really solves this problem since I have no working zwave yet( I am too busy these days). Dr. Wang, can you help test again?

**Comment by senatorjo** [comment]
The commit a85eb9c95968ff6a9f1d197b8a0bf3ee6b5fb31d  change location of .gitignore from src/app/wkdeploy/java to sec/app/wkdeploy since the whole src/app/wkdeploy/java folder will be deleted everytime deployment is in process.
