### ISSUE TITLE
Don't generate the #ifdef ENABLE_WUCLASS_XXXX for a wuclass

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#9]
Currently, we will generate the conditional compilation. However, we need to put the #define manually in the nativewuclasses.h. Therefore, the wuclass will not compiled unless we edit the native_wuclasses.h. I think that we don;t really need the #ifdef here since we have generate the regiter_wuclass in the native_wuclasses.c already. The compiler will include only used modules. The #ifdef will not save too much. Or we need to generate native_wuclasses.h as well in the code generator.

**Comment by pencilcheck** [comment]
Wait, I don't remember we were generating this in codegen.py, must have been the new code added by Niels or other students. Can you explain a bit more on this issue? I'm not sure if I understand the real issue here.

**Comment by wycc** [comment]
The current code gen never generate this. However, the codegen generate the
usage of it for each wuclass. Therefore, when we add a new wuclass, we need
to add the ENABLE_XXXX here so that it will be included in the compilation.

In my point of view, this MACRO is not required any more since we have
enable_wuclasses.xml already. The compiler will skip the module if it is
not used at all.

2013/8/31 Penn Su notifications@github.com

**Comment by pencilcheck** [comment]
Ok, fixed in my local copy

**Comment by pencilcheck** [comment]
Fixed some typos today, forgot to remove endif as well.
