### ISSUE TITLE
If we use the same component in different page, they will be map twice

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#90]
We should not map the component multiple times.

**Comment by wycc** [comment]
![a](https://f.cloud.github.com/assets/457473/1461226/dbccd902-449d-11e3-8ebb-ec72a2fc6776.png)

In this example, the Threshold is used in two pages. It should be shown once only.

**Comment by wycc** [comment]
This is not displayed issue only. It will actually create unusable result since the component_index are incorrect.

**Comment by wycc** [comment]
Please merge the components before we call the mapper.

**Comment by wycc** [comment]
4fbbbb103403a27a72819c1ed1860229fa87a9e6

This patch merge the components before we iterate the whole list. It works for me now,

**Comment by senatorjo** [comment]
Further updated the algorithm here after new data structure, should be working after commit 11e29552ec54503939e2495542050982362ca002.
