### ISSUE TITLE
2 Issues with the default code for a new wuclass

### ISSUE THREAD

**Issue by nielsreijers** [wukong-m2m/wukong-darjeeling#92]
If the class is called "Hello2", the default code in the code editor:
- tries to import GENERATEDHello2.h, while the codegen generates GENERATEDwuclass_hello2.c.
- contains a stub for wuclass_Hello2_update and wuclass_Hello2_setup, while the VM expects wuclass_hello2_update and wuclass_hello2_setup.

**Comment by nielsreijers** [comment]
Also, it generates a 
#ifdef ENABLE_WUCLASS_Hello2
line, which means the code inside isn't compiled. (actually we can probably get rid of all the ENABLE_WUCLASS_\* code.

**Comment by wycc** [comment]
Yes, we need to get rid of the ENABLE_xxxxx macro.

**Comment by nielsreijers** [comment]
ENABLE_WUCLASS_\* has been removed. Other two issues remain (at least I didn't fix them yet)
