### ISSUE TITLE
Pertorm discovery the new added device

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#97]
When we add a new device in the Node Editor, we should do a discovery for the single device to udpate the device cache.

**Comment by pencilcheck** [comment]
It should be as simple as adding a line to redo the discovery for that particular node.

**Comment by wycc** [comment]
This looks like the duplicated issue with #20.

2013/11/5 Penn Su notifications@github.com

**Comment by pencilcheck** [comment]
Let's focus on #20
